version: '1'

services:
  node-manager:
    image: protocol-sn-node-manager:latest
    ports:
      - 8081:8080
    depends_on:
      - db
  db:
    image: postgres:15.7
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: node-manager
    ports:
      - 5432:5432
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql