micronaut:
  application:
    name: node-manager
  server:
    port: 8080
  security:
    token:
      jwt:
        signatures:
          jwks:
            keycloak:
              url: http://localhost:9080/realms/Social-Network-Ecosystem/protocol/openid-connect/certs
    endpoints:
      login:
        enabled: true
      logout:
        get-allowed: true
    authentication: idtoken
    oauth2:
      clients:
        keycloak:
          client-secret: HELxIV5Zh1wQyCbBQmWesTOG7CsZM5P8
          client-id: node-manager
          openid:
            issuer: http://localhost:9080/realms/Social-Network-Ecosystem
