micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        mapping: /swagger-ui/**
        paths: classpath:META-INF/swagger/views/swagger-ui
  security:
    oauth2:
      clients:
        keycloak:
          client-secret: node-manager-secret
          client-id: node-manager
          openid:
            issuer: http://keycloak:8080/realms/social-network-ecosystem
    endpoints:
      login:
        enabled: true
      logout:
        get-allowed: true
    token:
      jwt:
        signatures:
          jwks:
            keycloak:
              url: http://localhost:9080/realms/social-network-ecosystem/protocol/openid-connect/certs
    intercept-url-map:
      - pattern: /swagger/**
        access: isAnonymous()
      - pattern: /swagger-ui/**
        access: isAnonymous()
  application:
    name: node-manager

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none

flyway:
  datasources:
    default:
      enabled: true
      locations: db/migrations

logger:
  levels:
    io.micronaut.security: DEBUG