micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        mapping: /swagger-ui/**
        paths: classpath:META-INF/swagger/views/swagger-ui
  security:
    oauth2:
      clients:
        keycloak:
          client-secret: HELxIV5Zh1wQyCbBQmWesTOG7CsZM5P8
          client-id: node-manager
          openid:
            issuer: http://localhost:9080/realms/social-network-ecosystem
    authentication: idtoken
    endpoints:
      login:
        enabled: true
      logout:
        get-allowed: true
    token:
      jwt:
        signatures:
          jwks:
            keycloak:
              url: http://host.docker.internal:9080/realms/social-network-ecosystem/protocol/openid-connect/certs
    intercept-url-map:
      - pattern: /swagger/**
        access: isAnonymous()
      - pattern: /swagger-ui/**
        access: isAnonymous()
  application:
    name: node-manager

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://db:5432/node-manager
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true
      locations: db/migrations