micronaut:
  application:
    name: node-manager

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none

flyway:
  datasources:
    default:
      enabled: true
      locations: db/migrations

logger:
  levels:
    coop.stlma.tech.protocolsn: DEBUG