datasources:
  default:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5443/nodemanager
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
    dialect: POSTGRES

micronaut:
  security:
    oauth2:
      clients:
        keycloak:
          client-secret: node-manager-secret
          client-id: node-manager
          openid:
            issuer: http://localhost:9080/realms/Social-Network-Ecosystem