datasources:
  default:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5443/nodemanager
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
    dialect: POSTGRES

micronaut:
  application:
    name: node-manager
  server:
    port: 8080
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        mapping: /swagger-ui/**
        paths: classpath:META-INF/swagger/views/swagger-ui
  security:
    token:
      jwt:
        signatures:
          jwks:
            keycloak:
              url: http://localhost:9080/realms/social-network-ecosystem/protocol/openid-connect/certs
    oauth2:
      clients:
        keycloak-client:
          client-secret: node-manager-secret
          client-id: node-manager
          grant-type: client_credentials
          token:
            url: http://localhost:9080/realms/social-network-ecosystem/protocol/openid-connect/token
            auth-method: client_secret_post
          client-credentials:
            uri-regex: (http://localhost:8081/){1}(.)*
          openid:
            issuer: http://localhost:9080/realms/social-network-ecosystem
        local-keycloak:
          client-secret: node-manager-secret
          client-id: node-manager
          openid:
            issuer: http://localhost:9080/realms/social-network-ecosystem
    authentication: cookie
    intercept-url-map:
      - pattern: /favicon.ico
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /swagger/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        httpMethod: GET
        access:
          - isAnonymous()

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none

flyway:
  datasources:
    default:
      enabled: true
      locations: db/migrations

logger:
  levels:
    coop.stlma.tech.protocolsn: DEBUG
    io.micronaut.data: TRACE
    io.micronaut.http: DEBUG

grpc:
  server:
    port: 8090