package coop.stlma.tech.protocolsn.registration.data.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.UUID;

/**
 * Database entity representing a registered plugin.
 *
 * @author John
 */
@Entity
@Table(name = "registered_plugins")
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
public class PluginRegistrationEntity {

    /**
     * Autogenerated UUID serving as the primary key.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * Distinguishing name for the plugin
     */
    @Column(name = "plugin_name")
    private String pluginName;

    /**
     * Host URL of the plugin
     */
    @Column(name = "plugin_location")
    private String pluginLocation;
}
